spring:
  datasource:
    url: jdbc:mysql://localhost:3306/connect-invoice-service
    username: prodapt
    password: we1c@me1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#  application:
#    name: record-service
#  server:
#    port: 3333

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#jwt:
#  private-key: classpath:app.key
#  public-key: classpath:app.pub
